
import streamlit as st
import unicodedata
from PIL import Image

# ユーザーの入力を判定
def judge(user_input, correct_answer):
    if user_input:
        if user_input == correct_answer:
            st.success("正解！")
            return True
        else:
            st.error("不正解…")

maegaki_btn = st.button('まえがきを見る')
if maegaki_btn:
    st.caption('まえがき')
    st.caption('暇だったのと、ノリと勢いで、数学の解説記事を作ってみました。')
    st.caption('この単元（平方根）は多分中３の「展開と因数分解」の次にやるのかな。')
    st.caption('いかんせんこの単元は量が多いから、多分、平方根−５ぐらいまではやるかもしれない。')
    st.caption('まあ僕のモチベ次第ですね。')
    cancel_btn = st.button('閉じる')

st.title('平方根-１')
st.caption('はじめに一つ問題を出そう。')
st.caption('ある数を２乗すると４になった。このある数はなんだろうか？')
st.caption('一つは簡単にわかるだろう。そう２だ。２を２乗すると４になる。')
st.caption('しかし実はもう一つ答がある。−２だ。−２を２乗すると４になる。')
st.caption('−２は思いつかなかった人が多いのではないだろうか？')
st.caption('では少し聞き方を変えてもう一問。２乗すると9になる数はなんだろうか？')
st.caption('')
user_input = st.text_input("「⚪と⚪︎」のように解答してください:", key="input_1")
user_input = user_input.replace('と', '')
user_input = user_input.replace('ー', '-')
user_input = user_input.replace('−', '-')
user_input = user_input.replace('　', '')
user_input = user_input.replace(' ', '')
user_input = unicodedata.normalize('NFKC', user_input)
if judge(user_input, '3-3'):
    st.caption('')
    st.caption('このように、')
    st.caption('ある数 a を２乗すると、ある数 b になるとき、a は b の平方根（へいほうこん）と呼ばれる。')
    st.caption('もう少し簡単にいうと、')
    st.caption('「2乗すると、ある数Xになる数字」を、Xの平方根という。')
    st.caption('例えば、「２乗すると、4になる数字」、すなわち４の平方根と考えよう。')
    st.caption('これは、はじめに出した問題の２と−２である。')
    st.caption('では９の平方根は？')
    st.caption('そう３と−３だ。')
    st.caption('「平方」は２乗のこと。２乗の根だから平方根なのだ。')
    st.caption('また、０を除く全ての数には必ず２つの平方根が存在する。')
    st.caption('4の平方根の(2, -2)や、9の平方根の(3, -3)のようにだ。')
    st.caption('０に２つの平方根が存在しないのは、+0と−0が同じ数だからである。')
    heihoukon_setumei = Image.open('heihoukon_setumei.png')
    st.image(heihoukon_setumei, caption='平方根の例')
    st.caption('では、ここまで理解したところで、少し練習をしよう。')
    st.caption('問題：16の平方根を答えよ。')
    st.caption('')
    user_input = st.text_input("「⚪と⚪︎」のように解答してください:", key="input_2")
    user_input = user_input.replace('と', '')
    user_input = user_input.replace('ー', '-')
    user_input = user_input.replace('−', '-')
    user_input = user_input.replace('　', '')
    user_input = user_input.replace(' ', '')
    user_input = unicodedata.normalize('NFKC', user_input)
    if judge(user_input, '4-4'):
        st.caption('')
        st.caption('ここまでで、平方根の基本的な概念については理解できたことだろう。')
        st.caption('では、次の質問について少し考えてもらいたい。')
        st.caption('２の平方根はなんだろうか？ ')
        st.caption('')
        ninoheihoukon = Image.open('ninoheihoukon.png')
        st.image(ninoheihoukon, caption='図で表したもの')
        st.caption('')
        st.caption('どうだろう？四角に入る数字は見つけられただろうか？')
        st.caption('おそらくこの四角に入る数字は見つけられないであろう。')
        st.caption('それでは答を発表すると、２の平方根は、')
        st.caption('')
        st.caption('1.414213562373095048801688724209698078569671875376948073176679737990732478462107038850387534327641...')
        st.caption('')
        st.caption('である。')
        st.caption('もちろんこれで終わりではない。この数は無限に続くのだ。')
        st.caption('この無限に続く数を２乗すると、おどろくべきことに、ちょうど２になるのだ。')
        st.caption('')
        st.caption('しかしこのままではどうも扱いづらい。')
        st.caption('そこで、古代の数学者たちは、この数を、')
        st.latex(r"\sqrt{2}")
        st.caption('と表すことにした。')
        ru_toninoatai = Image.open('ru-toninoatai.png')
        st.image(ru_toninoatai, caption='ルート２の値')
        st.latex(r"\sqrt{}")
        st.caption('この記号は、「ルート」と読み、平方根を表す。')
        st.latex(r"\sqrt{2}")
        st.caption('これは、「ルート２」と読む。')
        st.caption('')
        st.caption('つまり、２の平方根は、')
        st.latex(r"\sqrt{2}")
        st.caption('と')
        st.latex(r"-\sqrt{2}")
        st.caption('である。')
        st.caption('')
        st.caption('このあたりから、少しややこしくなってくるため、頭を抱える人がではじめる。')
        st.caption('もし読者の中に、このあたりで頭を抱えている人がいたら、下の図を見れば、完全に理解することができるだろう。')
        st.caption('')
        table_before = Image.open('table_before.png')
        st.image(table_before)
        yazirusi = Image.open('yazirusi.png')
        st.image(yazirusi)
        table_after = Image.open('table_after.png')
        st.image(table_after)
        st.caption('')
        st.caption('では、最後に問題を何問かだそう。')
        st.caption('')
        st.caption('問題１：25の平方根を答えよ。')
        st.caption('')
        user_input = st.text_input("「⚪と⚪︎」のように解答してください:", key="input_3")
        user_input = user_input.replace('と', '')
        user_input = user_input.replace('ー', '-')
        user_input = user_input.replace('−', '-')
        user_input = user_input.replace('　', '')
        user_input = user_input.replace(' ', '')
        user_input = unicodedata.normalize('NFKC', user_input)
        judge(user_input, '5-5')
        st.caption('')
        st.caption('問題２：2の平方根を答えよ。')
        st.caption('')
        user_input = st.text_input("「ルート⚪とルート⚪︎」のように解答してください:", key="input_4")
        user_input = user_input.replace('と', '')
        user_input = user_input.replace('ルート', '')
        user_input = user_input.replace('ー', '-')
        user_input = user_input.replace('−', '-')
        user_input = user_input.replace('　', '')
        user_input = user_input.replace(' ', '')
        user_input = unicodedata.normalize('NFKC', user_input)
        judge(user_input, '2-2')
        st.caption('')
        st.caption('問題３：5の平方根を答えよ。')
        st.caption('')
        user_input = st.text_input("「ルート⚪とルート⚪︎」のように解答してください:", key="input_5")
        user_input = user_input.replace('と', '')
        user_input = user_input.replace('ルート', '')
        user_input = user_input.replace('ー', '-')
        user_input = user_input.replace('−', '-')
        user_input = user_input.replace('　', '')
        user_input = user_input.replace(' ', '')
        user_input = unicodedata.normalize('NFKC', user_input)
        judge(user_input, '5-5')
        st.caption('')
        st.caption('問題４：１の平方根を答えよ。')
        st.caption('')
        user_input = st.text_input("「⚪と⚪︎」のように解答してください:", key="input_6")
        user_input = user_input.replace('と', '')
        user_input = user_input.replace('ー', '-')
        user_input = user_input.replace('−', '-')
        user_input = user_input.replace('　', '')
        user_input = user_input.replace(' ', '')
        user_input = unicodedata.normalize('NFKC', user_input)
        if judge(user_input, '1-1'):
            st.caption('')
            st.caption('これで平方根の基本的な概念については理解できたことだろう。')
            st.caption('次回は、平方根の計算方法について解説する。')
            st.caption('')
            st.caption('')
            st.caption('')
            st.caption('P.S.')
            st.caption('わかりやすかったかな？')
            st.caption('僕のやる気があれば、次回も作るかもしれません。')
            pc_jpg = Image.open('pc.jpg')
            st.image(pc_jpg, caption='このサイト作成中のデスク')